#ifndef GAME_PAD_NUMBER_H_
#define GAME_PAD_NUMBER_H_

#include <DxLib.h>

// ゲームパッドの番号
enum GamePadNumber
{
	GAME_PAD_NUMBER_1 = DX_INPUT_PAD1,
	GAME_PAD_NUMBER_2 = DX_INPUT_PAD2,
	GAME_PAD_NUMBER_3 = DX_INPUT_PAD3,
	GAME_PAD_NUMBER_4 = DX_INPUT_PAD4,
	GAME_PAD_NUMBER_5 = DX_INPUT_PAD5,
	GAME_PAD_NUMBER_6 = DX_INPUT_PAD6,
	GAME_PAD_NUMBER_7 = DX_INPUT_PAD7,
	GAME_PAD_NUMBER_8 = DX_INPUT_PAD8,
	GAME_PAD_NUMBER_9 = DX_INPUT_PAD9,
	GAME_PAD_NUMBER_10 = DX_INPUT_PAD10,
	GAME_PAD_NUMBER_11 = DX_INPUT_PAD11,
	GAME_PAD_NUMBER_12 = DX_INPUT_PAD12,
	GAME_PAD_NUMBER_13 = DX_INPUT_PAD13,
	GAME_PAD_NUMBER_14 = DX_INPUT_PAD14,
	GAME_PAD_NUMBER_15 = DX_INPUT_PAD15,
	GAME_PAD_NUMBER_16 = DX_INPUT_PAD16,
};

#endif // !GAME_PAD_NUMBER_H_